<?
return array(
	"ltext" => "Logo blue",
	"limg" => "Logo img",
	"indent-top" => "Padding top 5px",
	"txt-up" => "Uppercase",
	"border-none" => "Border none",
	"bg-none" => "Background none",
	"dis-block" => "Display block",
	"dis-inblock" => "Display inline-block",
	"marg-left-0" => "Margin left 0",
	"marg-right-0" => "Margin right 0",
	"marg-left-right-0" => "Margin left right 0",
	"last-mbot" => "Margin bottom 0",
	"last-pbot" => "Padding bottom 0",
	"last-mpbot" => "Margin padding bottom 0",
	"col" => "Blue",
	"top" => "Padding top 5px",
	"left" => "Margin left -5px",
	"left-1" => "Margin left 20px",
	"clear" => "Clear",
	"fleft" => "Left",
	"fright" => "Right",
	"indenth2" => "Margin 44px 0 13px 0",
	"indenth2-1" => "Padding 6px 0 9px 0",
	"indenth2-2" => "Padding 53px 0 13px 0",
	"link" => "Link",
	"btn" => "Button",
	"whit-sp" => "Nowrap",
	"quote" => "Quote",
	"link-form" => "Link form",
	"telephone-cont" => "Footer phone",
	"icon" => "Icon Facebook",
	"icon-1" => "Icon Twitter",
);
?>